# Generated by Django 2.1.7 on 2019-03-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'amount']},
        ),
    ]
