# Generated by Django 2.1.7 on 2019-04-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramgroup'),
        ('expenses', '0005_auto_20190402_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bot.TelegramGroup'),
            preserve_default=False,
        ),
    ]
