# Generated by Django 2.1.7 on 2019-04-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_tag_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(related_name='expenses', to='expenses.Tag'),
        ),
    ]
