# Generated by Django 2.1.7 on 2019-04-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20190419_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['date']},
        ),
    ]
