# Generated by Django 2.1.7 on 2019-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='name',
            field=models.CharField(default='initial', max_length=256),
            preserve_default=False,
        ),
    ]
