# Generated by Django 3.2.13 on 2022-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
